const UNIVERSITIES_DATA = [
            // GERMANY (9 universities)
            {
                id: 0,
                name: "Technical University of Berlin (TU Berlin)",
                country: "Germany",
                program: "B.Sc. Artificial Intelligence & Data Engineering",
                language: "English",
                lat: 52.5126,
                lng: 13.3266,
                tuitionPerYear: "€350",
                livingPerYear: "€10,800-15,600",
                duration: 3,
                cost: "€33-48k total",
                costMin: 33000,
                costMax: 48000,
                erasmusPlus: true,
                erasmusPartners: "Extensive",
                classification: "Reach",
                fitScore: 5,
                citySize: "Large city",
                admissionsEmail: "international-department@tu.berlin.de",
                openHouseDates: "TBD - Contact admissions (new program Oct 2025)",
                visitInfo: "Berlin campus tours available - contact International Office",
                visitUrl: "https://www.tu.berlin/en/international/students-1/international-students",
                highlights: [
                    "🆕 BRAND NEW PROGRAM - First intake October 2025!",
                    "Top German technical university (#12 THE Rankings)",
                    "BERLIN - Europe's startup & tech capital 🏙️",
                    "BIFOLD Institute - 12 research groups in Big Data & ML",
                    "Machine Learning Group with 50+ researchers",
                    "Industry partnerships: Siemens, BMW, SAP, Deutsche Bahn",
                    "Science of Intelligence Cluster (with Humboldt University)",
                    "Practically FREE for EU students (€350/year tuition)",
                    "Same cost as small-town universities but IN BERLIN!",
                    "Access to Berlin's thriving tech ecosystem & startups"
                ],
                url: "https://www.tu.berlin/en/studying/study-programs/all-programs-offered"
            },
            {
                id: 1,
                name: "University of Passau",
                country: "Germany",
                program: "BSc Artificial Intelligence",
                language: "English",
                lat: 48.5665,
                lng: 13.4318,
                tuitionPerYear: "€350",
                livingPerYear: "€12,000-13,200",
                duration: 3,
                cost: "€37-41k total",
                costMin: 37000,
                costMax: 41000,
                erasmusPlus: true,
                erasmusPartners: "250+",
                classification: "Match",
                fitScore: 5,
                citySize: "Small city",
                admissionsEmail: "advice@uni-passau.de",
                openHouseDates: "March 21, 2026",
                visitInfo: "Campus tours available throughout orientation week (Sept 29 - Oct 12, 2025)",
                visitUrl: "https://www.uni-passau.de/en/open-days",
                highlights: [
                    "Dedicated AI bachelor's program in English",
                    "Nearly free tuition (€350/year)",
                    "Beautiful campus on the Danube",
                    "Erasmus+ with 250+ partner universities"
                ],
                url: "https://www.uni-passau.de/en/bsc-artificial-intelligence"
            },
            {
                id: 2,
                name: "University of Bayreuth",
                country: "Germany",
                program: "BSc Data Science & AI",
                language: "English",
                lat: 49.9294,
                lng: 11.5858,
                tuitionPerYear: "€350",
                livingPerYear: "€12,000-13,200",
                duration: 3,
                cost: "€37-41k total",
                costMin: 37000,
                costMax: 41000,
                erasmusPlus: true,
                erasmusPartners: "150+",
                classification: "Match",
                fitScore: 5,
                citySize: "Small city",
                admissionsEmail: "studierendenkanzlei@uni-bayreuth.de",
                openHouseDates: "Spring 2026",
                visitInfo: "Campus tours during orientation week (Oct 2025)",
                visitUrl: "https://www.uni-bayreuth.de/en/study",
                highlights: [
                    "Dedicated Data Science & AI program",
                    "English-taught at German prices",
                    "Modern campus with excellent facilities",
                    "Erasmus+ with 150+ partners"
                ],
                url: "https://www.uni-bayreuth.de/en/study/degree-programmes/bachelor/data-science-ai"
            },
            {
                id: 3,
                name: "TH Deggendorf",
                country: "Germany",
                program: "BSc Applied AI",
                language: "English",
                lat: 48.8288,
                lng: 12.9606,
                tuitionPerYear: "€350",
                livingPerYear: "€10,800-12,000",
                duration: 3.5,
                cost: "€39-43k total",
                costMin: 39000,
                costMax: 43000,
                erasmusPlus: true,
                erasmusPartners: "200+",
                classification: "Safety",
                fitScore: 4,
                citySize: "Small town",
                admissionsEmail: "studentservice@th-deg.de",
                openHouseDates: "Check website",
                visitInfo: "Individual campus visits available",
                visitUrl: "https://www.th-deg.de/en/bai-b",
                highlights: [
                    "Applied, hands-on AI program",
                    "Includes mandatory internship semester",
                    "Multiple campuses across Bavaria",
                    "48% international students"
                ],
                url: "https://www.th-deg.de/en/bai-b"
            },
            {
                id: 4,
                name: "Saarland University",
                country: "Germany",
                program: "BSc Computer Science (AI track)",
                language: "English",
                lat: 49.2545,
                lng: 7.0418,
                tuitionPerYear: "€350",
                livingPerYear: "€12,000-13,200",
                duration: 3,
                cost: "€37-41k total",
                costMin: 37000,
                costMax: 41000,
                erasmusPlus: true,
                erasmusPartners: "Extensive network",
                classification: "Match",
                fitScore: 4,
                citySize: "Mid-size city",
                admissionsEmail: "studium@uni-saarland.de",
                openHouseDates: "Spring 2026",
                visitInfo: "DFKI AI Research Center tours available",
                visitUrl: "https://www.uni-saarland.de/en/study/visit.html",
                highlights: [
                    "Home to German AI Research Center (DFKI)",
                    "Strong research reputation",
                    "Near France/Luxembourg border",
                    "Franco-German University programs"
                ],
                url: "https://www.uni-saarland.de/en/study/programmes/bachelor/computer-science.html"
            },
            {
                id: 5,
                name: "University of Tübingen",
                country: "Germany",
                program: "BSc Computer Science",
                language: "German (mostly)",
                lat: 48.5216,
                lng: 9.0576,
                tuitionPerYear: "€350",
                livingPerYear: "€13,200-14,400",
                duration: 3,
                cost: "€41-44k total",
                costMin: 41000,
                costMax: 44000,
                erasmusPlus: true,
                erasmusPartners: "450+",
                classification: "Reach",
                fitScore: 3,
                citySize: "Mid-size city",
                admissionsEmail: "studium@uni-tuebingen.de",
                openHouseDates: "Check website",
                visitInfo: "Campus tours available",
                visitUrl: "https://uni-tuebingen.de",
                highlights: [
                    "Elite German university",
                    "Strong AI research (Max Planck Institute)",
                    "Erasmus+ 450+ partners (very extensive)",
                    "Mostly German-taught (limited for international)"
                ],
                url: "https://uni-tuebingen.de/en/study/information-prospective-students/degree-programs/computer-science/"
            },
            {
                id: 6,
                name: "FAU Erlangen-Nuremberg",
                country: "Germany",
                program: "BSc Data Science",
                language: "English/German",
                lat: 49.5975,
                lng: 11.0045,
                tuitionPerYear: "€350",
                livingPerYear: "€12,000-13,200",
                duration: 3,
                cost: "€37-41k total",
                costMin: 37000,
                costMax: 41000,
                erasmusPlus: true,
                erasmusPartners: "500+",
                classification: "Match",
                fitScore: 4,
                citySize: "Large city",
                admissionsEmail: "studienberatung@fau.de",
                openHouseDates: "Spring 2026",
                visitInfo: "Regular campus tours",
                visitUrl: "https://www.fau.eu",
                highlights: [
                    "Largest Erasmus+ network in Germany (500+)",
                    "Strong CS and engineering reputation",
                    "Located in Bavaria's tech corridor",
                    "ATHENS program participant"
                ],
                url: "https://www.fau.eu/education/degree-programmes-a-z/data-science-bsc/"
            },
            {
                id: 7,
                name: "TH Rosenheim",
                country: "Germany",
                program: "BSc Artificial Intelligence",
                language: "English",
                lat: 47.8564,
                lng: 12.1270,
                tuitionPerYear: "€350",
                livingPerYear: "€13,200-14,400",
                duration: 3.5,
                cost: "€47-52k total",
                costMin: 47000,
                costMax: 52000,
                erasmusPlus: true,
                erasmusPartners: "100+",
                classification: "Match",
                fitScore: 4,
                citySize: "Small city",
                admissionsEmail: "studienberatung@th-rosenheim.de",
                openHouseDates: "Check website",
                visitInfo: "Campus visits by appointment",
                visitUrl: "https://www.th-rosenheim.de",
                highlights: [
                    "Applied AI program",
                    "Near Munich and Alps",
                    "Strong industry partnerships",
                    "Includes practical semester"
                ],
                url: "https://www.th-rosenheim.de/en/study/study-programs/bachelor/artificial-intelligence-beng"
            },
            {
                id: 8,
                name: "THI Ingolstadt",
                country: "Germany",
                program: "BSc Artificial Intelligence",
                language: "English",
                lat: 48.7665,
                lng: 11.4257,
                tuitionPerYear: "€350",
                livingPerYear: "€12,000-13,200",
                duration: 3.5,
                cost: "€43-47k total",
                costMin: 43000,
                costMax: 47000,
                erasmusPlus: true,
                erasmusPartners: "120+",
                classification: "Safety",
                fitScore: 4,
                citySize: "Mid-size city",
                admissionsEmail: "studienberatung@thi.de",
                openHouseDates: "Multiple dates",
                visitInfo: "Regular campus tours",
                visitUrl: "https://www.thi.de",
                highlights: [
                    "Strong automotive industry connections (Audi HQ)",
                    "Applied sciences focus",
                    "Modern facilities",
                    "Industry internship opportunities"
                ],
                url: "https://www.thi.de/en/study/bachelors-degree-programmes/artificial-intelligence"
            },

            // NETHERLANDS (6 universities)
            {
                id: 9,
                name: "Maastricht University",
                country: "Netherlands",
                program: "BSc Data Science & AI",
                language: "English",
                lat: 50.8483,
                lng: 5.6889,
                tuitionPerYear: "€2,314",
                livingPerYear: "€10,800-12,000",
                duration: 3,
                cost: "€39-43k total",
                costMin: 39000,
                costMax: 43000,
                erasmusPlus: true,
                erasmusPartners: "300+",
                classification: "Match",
                fitScore: 5,
                citySize: "Mid-size city",
                admissionsEmail: "studyadvisor-dke@maastrichtuniversity.nl",
                openHouseDates: "March 2026",
                visitInfo: "Open days and campus tours throughout year",
                visitUrl: "https://www.maastrichtuniversity.nl/education/bachelor/data-science-and-artificial-intelligence",
                highlights: [
                    "Problem-based learning approach",
                    "International environment (50% international)",
                    "Near Belgium/Germany border",
                    "Erasmus+ with 300+ partners"
                ],
                url: "https://www.maastrichtuniversity.nl/education/bachelor/data-science-and-artificial-intelligence"
            },
            {
                id: 10,
                name: "VU Amsterdam",
                country: "Netherlands",
                program: "BSc Artificial Intelligence",
                language: "English",
                lat: 52.3341,
                lng: 4.8656,
                tuitionPerYear: "€2,314",
                livingPerYear: "€14,400-18,000",
                duration: 3,
                cost: "€50-61k total",
                costMin: 50000,
                costMax: 61000,
                erasmusPlus: true,
                erasmusPartners: "250+",
                classification: "Match",
                fitScore: 5,
                citySize: "Large city",
                admissionsEmail: "info@vu.nl",
                openHouseDates: "Multiple open days",
                visitInfo: "Regular campus tours in Amsterdam",
                visitUrl: "https://vu.nl/en/education/bachelor/artificial-intelligence",
                highlights: [
                    "Top-tier AI research program",
                    "Amsterdam tech hub location",
                    "Strong industry connections",
                    "HIGH living costs (Amsterdam)"
                ],
                url: "https://vu.nl/en/education/bachelor/artificial-intelligence"
            },
            {
                id: 11,
                name: "University of Groningen",
                country: "Netherlands",
                program: "BSc Artificial Intelligence",
                language: "English",
                lat: 53.2194,
                lng: 6.5665,
                tuitionPerYear: "€2,314",
                livingPerYear: "€10,800-12,000",
                duration: 3,
                cost: "€39-43k total",
                costMin: 39000,
                costMax: 43000,
                erasmusPlus: true,
                erasmusPartners: "400+",
                classification: "Safety",
                fitScore: 4,
                citySize: "Mid-size city",
                admissionsEmail: "info@rug.nl",
                openHouseDates: "Spring 2026",
                visitInfo: "Open days and campus tours",
                visitUrl: "https://www.rug.nl/bachelors/artificial-intelligence/",
                highlights: [
                    "Vibrant student city atmosphere",
                    "Very affordable for Netherlands",
                    "Erasmus+ with 400+ partners (extensive)",
                    "Strong international community"
                ],
                url: "https://www.rug.nl/bachelors/artificial-intelligence/"
            },
            {
                id: 12,
                name: "Leiden University",
                country: "Netherlands",
                program: "BSc Data Science & AI",
                language: "English",
                lat: 52.1579,
                lng: 4.4844,
                tuitionPerYear: "€2,314",
                livingPerYear: "€12,000-14,400",
                duration: 3,
                cost: "€43-50k total",
                costMin: 43000,
                costMax: 50000,
                erasmusPlus: true,
                erasmusPartners: "200+",
                classification: "Match",
                fitScore: 5,
                citySize: "Mid-size city",
                admissionsEmail: "studiechoice@liacs.leidenuniv.nl",
                openHouseDates: "Multiple dates",
                visitInfo: "Campus tours available",
                visitUrl: "https://www.universiteitleiden.nl/en/education/study-programmes/bachelor/artificial-intelligence",
                highlights: [
                    "Oldest university in Netherlands (1575)",
                    "Beautiful historic city",
                    "League of European Research Universities",
                    "Near The Hague and Amsterdam"
                ],
                url: "https://www.universiteitleiden.nl/en/education/study-programmes/bachelor/artificial-intelligence"
            },
            {
                id: 13,
                name: "Breda University",
                country: "Netherlands",
                program: "BSc Applied Data Science & AI",
                language: "English",
                lat: 51.5719,
                lng: 4.7683,
                tuitionPerYear: "€2,314",
                livingPerYear: "€10,800-12,000",
                duration: 4,
                cost: "€52-57k total",
                costMin: 52000,
                costMax: 57000,
                erasmusPlus: true,
                erasmusPartners: "100+",
                classification: "Safety",
                fitScore: 4,
                citySize: "Mid-size city",
                admissionsEmail: "info@buas.nl",
                openHouseDates: "Check website",
                visitInfo: "Open days and campus tours",
                visitUrl: "https://www.buas.nl/en/programmes/applied-data-science-and-artificial-intelligence",
                highlights: [
                    "Applied sciences - very practical",
                    "4 years including internship",
                    "Strong industry connections",
                    "Focus on real-world applications"
                ],
                url: "https://www.buas.nl/en/programmes/applied-data-science-and-artificial-intelligence"
            },
            {
                id: 14,
                name: "Zuyd University",
                country: "Netherlands",
                program: "BSc Applied Data Science & AI",
                language: "English",
                lat: 50.8514,
                lng: 5.6909,
                tuitionPerYear: "€2,314",
                livingPerYear: "€10,800-12,000",
                duration: 4,
                cost: "€52-57k total",
                costMin: 52000,
                costMax: 57000,
                erasmusPlus: true,
                erasmusPartners: "Extensive",
                classification: "Safety",
                fitScore: 4,
                citySize: "Mid-size city",
                admissionsEmail: "info@zuyd.nl",
                openHouseDates: "Multiple dates",
                visitInfo: "Campus tours available",
                visitUrl: "https://www.zuyd.nl/en/programmes/applied-data-science-and-artificial-intelligence",
                highlights: [
                    "Applied sciences focus",
                    "Maastricht area (near Belgium/Germany)",
                    "4 years with practical experience",
                    "Euregional connections"
                ],
                url: "https://www.zuyd.nl/en/programmes/applied-data-science-and-artificial-intelligence"
            },

            // BELGIUM (1 university)
            {
                id: 15,
                name: "KdG Antwerp",
                country: "Belgium",
                program: "BSc Applied Computer Science (AI Specialization)",
                language: "English",
                lat: 51.2194,
                lng: 4.4025,
                tuitionPerYear: "€1,157",
                livingPerYear: "€10,200-11,400",
                duration: 3,
                cost: "€34-38k total",
                costMin: 34000,
                costMax: 38000,
                erasmusPlus: true,
                erasmusPartners: "150+",
                classification: "Safety",
                fitScore: 5,
                citySize: "Large city",
                new: true,
                admissionsEmail: "apply@kdg.be",
                openHouseDates: "Spring 2026",
                visitInfo: "Campus tours available - contact incoming.mit@kdg.be",
                visitUrl: "https://www.kdg.be/en/applied-computer-science",
                highlights: [
                    "🆕 NEWLY ADDED - Remember we discussed this!",
                    "100% ENGLISH-taught program",
                    "CHEAPEST English option (€34-38k total!)",
                    "AI Specialization built into program",
                    "Practical, hands-on approach",
                    "8-week internship in final year",
                    "No entrance exam - diploma + English B2",
                    "Antwerp - vibrant international city"
                ],
                url: "https://www.kdg.be/en/applied-computer-science"
            },

            // SPAIN (12 universities)
            {
                id: 16,
                name: "UPM Madrid",
                country: "Spain",
                program: "BSc Data Science & AI",
                language: "Spanish",
                lat: 40.4406,
                lng: -3.6758,
                tuitionPerYear: "€1,600-2,000",
                livingPerYear: "€10,800-12,000",
                duration: 4,
                cost: "€50-56k total",
                costMin: 50000,
                costMax: 56000,
                erasmusPlus: true,
                erasmusPartners: "400+",
                classification: "Reach",
                fitScore: 5,
                citySize: "Large city",
                admissionsEmail: "informacion.academica@upm.es",
                openHouseDates: "Spring 2026",
                visitInfo: "Campus tours available",
                visitUrl: "https://www.upm.es",
                highlights: [
                    "Top Spanish engineering university",
                    "Erasmus+ with 400+ partners (largest in Spain)",
                    "Madrid capital location",
                    "Taught in Spanish (C1 advantage!)"
                ],
                url: "https://www.upm.es/Estudiantes/Estudios_Titulaciones/EstudiosOficiales"
            },
            {
                id: 17,
                name: "UC3M Madrid",
                country: "Spain",
                program: "BSc Data Science & Engineering",
                language: "Spanish/English",
                lat: 40.3313,
                lng: -3.7643,
                tuitionPerYear: "€1,800-2,200",
                livingPerYear: "€10,800-12,000",
                duration: 4,
                cost: "€50-57k total",
                costMin: 50000,
                costMax: 57000,
                erasmusPlus: true,
                erasmusPartners: "300+",
                classification: "Match",
                fitScore: 5,
                citySize: "Large city",
                admissionsEmail: "informacion@uc3m.es",
                openHouseDates: "Multiple dates",
                visitInfo: "Campus tours at multiple locations",
                visitUrl: "https://www.uc3m.es/bachelor-degree/data-science",
                highlights: [
                    "Bilingual program (Spanish/English)",
                    "Excellent reputation in Spain",
                    "Strong international focus",
                    "Erasmus+ with 300+ partners"
                ],
                url: "https://www.uc3m.es/bachelor-degree/data-science"
            },
            {
                id: 18,
                name: "University of Barcelona",
                country: "Spain",
                program: "BSc Data Science",
                language: "Spanish/Catalan",
                lat: 41.3874,
                lng: 2.1686,
                tuitionPerYear: "€2,400-2,800",
                livingPerYear: "€10,800-13,200",
                duration: 4,
                cost: "€53-64k total",
                costMin: 53000,
                costMax: 64000,
                erasmusPlus: true,
                erasmusPartners: "250+",
                classification: "Match",
                fitScore: 4,
                citySize: "Large city",
                admissionsEmail: "informacio@ub.edu",
                openHouseDates: "Spring 2026",
                visitInfo: "Campus tours available",
                visitUrl: "https://www.ub.edu/web/portal/en/",
                highlights: [
                    "Prestigious Spanish university",
                    "Beautiful Barcelona location",
                    "Spanish/Catalan language",
                    "Coimbra Group member"
                ],
                url: "https://www.ub.edu/portal/web/mathematics-computer-science/bachelor-s-degrees/-/ensenyament/detallEnsenyament/1061205"
            },
            {
                id: 19,
                name: "University of Valencia",
                country: "Spain",
                program: "BSc Data Science",
                language: "Spanish",
                lat: 39.4810,
                lng: -0.3396,
                tuitionPerYear: "€1,300-1,600",
                livingPerYear: "€9,600-10,800",
                duration: 4,
                cost: "€44-50k total",
                costMin: 44000,
                costMax: 50000,
                erasmusPlus: true,
                erasmusPartners: "350+",
                classification: "Match",
                fitScore: 4,
                citySize: "Large city",
                admissionsEmail: "estudiantes@uv.es",
                openHouseDates: "Multiple dates",
                visitInfo: "Campus tours available",
                visitUrl: "https://www.uv.es/uvweb/college/en/undergraduate-degrees/undergraduate-degrees/data-science-1285846094474/Titulacio.html",
                highlights: [
                    "Beach city with great weather",
                    "Very affordable for Spain",
                    "Erasmus+ with 350+ partners",
                    "Mediterranean lifestyle"
                ],
                url: "https://www.uv.es"
            },
            {
                id: 20,
                name: "UPC Barcelona",
                country: "Spain",
                program: "BSc Computer Science (AI/Data)",
                language: "Spanish/Catalan",
                lat: 41.3888,
                lng: 2.1129,
                tuitionPerYear: "€2,400-2,800",
                livingPerYear: "€10,800-13,200",
                duration: 4,
                cost: "€53-64k total",
                costMin: 53000,
                costMax: 64000,
                erasmusPlus: true,
                erasmusPartners: "300+",
                classification: "Reach",
                fitScore: 4,
                citySize: "Large city",
                admissionsEmail: "info.fr@upc.edu",
                openHouseDates: "Spring 2026",
                visitInfo: "Campus tours available",
                visitUrl: "https://www.upc.edu/en",
                highlights: [
                    "Top Spanish engineering university",
                    "Strong AI/Data Science track",
                    "TIME and ATHENS networks",
                    "Barcelona tech hub"
                ],
                url: "https://www.upc.edu/en/bachelors"
            },
            {
                id: 21,
                name: "IE University",
                country: "Spain",
                program: "BSc CS & AI (PRIVATE)",
                language: "English",
                lat: 40.9465,
                lng: -4.1203,
                tuitionPerYear: "€26,000-28,000",
                livingPerYear: "€10,800-12,000",
                duration: 4,
                cost: "€147-160k total",
                costMin: 147000,
                costMax: 160000,
                erasmusPlus: false,
                erasmusPartners: "Limited",
                classification: "Expensive",
                fitScore: 3,
                citySize: "Madrid/Segovia",
                admissionsEmail: "admissions@ie.edu",
                openHouseDates: "Multiple dates",
                visitInfo: "Campus tours available",
                visitUrl: "https://www.ie.edu/university/",
                highlights: [
                    "English-taught private university",
                    "VERY EXPENSIVE (€147-160k)",
                    "NOT RECOMMENDED - poor value",
                    "Limited Erasmus+ as private institution"
                ],
                url: "https://www.ie.edu/university/studies/academic-programs/bachelors-computer-science-artificial-intelligence/"
            },
            {
                id: 22,
                name: "UPNA Pamplona",
                country: "Spain",
                program: "BSc Computer Science",
                language: "English",
                lat: 42.8020,
                lng: -1.6374,
                tuitionPerYear: "€1,200-1,500",
                livingPerYear: "€8,400-9,600",
                duration: 4,
                cost: "€38-44k total",
                costMin: 38000,
                costMax: 44000,
                erasmusPlus: true,
                erasmusPartners: "200+",
                classification: "Safety",
                fitScore: 5,
                citySize: "Mid-size city",
                admissionsEmail: "admision@unavarra.es",
                openHouseDates: "Spring 2026",
                visitInfo: "Campus tours available",
                visitUrl: "https://www.unavarra.es/home/",
                highlights: [
                    "100% ENGLISH-taught program",
                    "EXCELLENT VALUE (€38-44k)",
                    "Very affordable living costs",
                    "Erasmus+ with 200+ partners"
                ],
                url: "https://www.unavarra.es/sites/grados/informatica/informatica-english.html"
            },
            {
                id: 23,
                name: "UPV Valencia",
                country: "Spain",
                program: "BSc Data Science",
                language: "Spanish/English",
                lat: 39.4810,
                lng: -0.3400,
                tuitionPerYear: "€1,400-1,700",
                livingPerYear: "€9,600-10,800",
                duration: 4,
                cost: "€44-50k total",
                costMin: 44000,
                costMax: 50000,
                erasmusPlus: true,
                erasmusPartners: "400+",
                classification: "Match",
                fitScore: 5,
                citySize: "Large city",
                admissionsEmail: "infopdi@upv.es",
                openHouseDates: "Multiple dates",
                visitInfo: "Campus tours available",
                visitUrl: "https://www.upv.es/index-en.html",
                highlights: [
                    "Spanish/English options available",
                    "Beach city location",
                    "Erasmus+ with 400+ partners (very extensive)",
                    "Excellent value for quality"
                ],
                url: "https://www.upv.es/titulaciones/GCIEDDATOS/indexi.html"
            },
            {
                id: 24,
                name: "UAB Barcelona",
                country: "Spain",
                program: "BSc Artificial Intelligence",
                language: "English",
                lat: 41.5009,
                lng: 2.1055,
                tuitionPerYear: "€2,500-3,000",
                livingPerYear: "€10,800-13,200",
                duration: 4,
                cost: "€53-65k total",
                costMin: 53000,
                costMax: 65000,
                erasmusPlus: true,
                erasmusPartners: "300+",
                classification: "Reach",
                fitScore: 5,
                citySize: "Large city",
                admissionsEmail: "informacio.graus@uab.cat",
                openHouseDates: "Spring 2026",
                visitInfo: "Campus tours available",
                visitUrl: "https://www.uab.cat/web/estudiar/graus/artificial-intelligence-1345467812802.html",
                highlights: [
                    "ENGLISH-taught AI program",
                    "Near Barcelona (15 min by train)",
                    "Worldwide Universities Network member",
                    "Higher Catalonia tuition rates"
                ],
                url: "https://www.uab.cat/web/estudiar/graus/artificial-intelligence-1345467812802.html"
            },
            {
                id: 25,
                name: "TECNUN San Sebastián",
                country: "Spain",
                program: "BSc AI Engineering",
                language: "Spanish/English",
                lat: 43.3001,
                lng: -1.9666,
                tuitionPerYear: "€10,000-12,000",
                livingPerYear: "€10,800-12,000",
                duration: 4,
                cost: "€83-96k total",
                costMin: 83000,
                costMax: 96000,
                erasmusPlus: true,
                erasmusPartners: "150+",
                classification: "Reach",
                fitScore: 4,
                citySize: "Mid-size city",
                admissionsEmail: "admisiones@tecnun.es",
                openHouseDates: "Multiple dates",
                visitInfo: "Campus tours available",
                visitUrl: "https://www.tecnun.es/en",
                highlights: [
                    "Bilingual Spanish/English",
                    "Part of University of Navarra",
                    "EXPENSIVE for Spain (semi-private)",
                    "Beautiful Basque Country location"
                ],
                url: "https://www.tecnun.es/en/ingenio/undergraduate-degrees/artificial-intelligence-engineering"
            },
            {
                id: 26,
                name: "Universidad de Zaragoza",
                country: "Spain",
                program: "BSc Computer Science",
                language: "Spanish",
                lat: 41.6488,
                lng: -0.8891,
                tuitionPerYear: "€1,200-1,500",
                livingPerYear: "€8,400-9,600",
                duration: 4,
                cost: "€38-44k total",
                costMin: 38000,
                costMax: 44000,
                erasmusPlus: true,
                erasmusPartners: "300+",
                classification: "Safety",
                fitScore: 3.5,
                citySize: "Large city",
                admissionsEmail: "informacion@unizar.es",
                openHouseDates: "Spring 2026",
                visitInfo: "Campus tours available",
                visitUrl: "https://www.unizar.es/",
                highlights: [
                    "Very affordable (€38-44k)",
                    "Spanish-taught program",
                    "Coimbra Group member",
                    "Good value for cost-conscious students"
                ],
                url: "https://www.unizar.es/grado-en-ingenieria-informatica"
            },

            {
                id: 27,
                name: "Universitat Pompeu Fabra (UPF)",
                country: "Spain",
                program: "BSc Data Science",
                language: "Spanish/English",
                lat: 41.4036,
                lng: 2.1960,
                tuitionPerYear: "€1,500-2,000",
                livingPerYear: "€10,800-13,200",
                duration: 4,
                cost: "€49-61k total",
                costMin: 49000,
                costMax: 61000,
                erasmusPlus: true,
                erasmusPartners: "250+",
                classification: "Match",
                fitScore: 5,
                citySize: "Large city",
                new: true,
                admissionsEmail: "informacio.graus@upf.edu",
                openHouseDates: "Spring 2026",
                visitInfo: "Campus tours at 22@ Innovation District",
                visitUrl: "https://www.upf.edu/web/graus/grau-en-ciencia-de-dades",
                highlights: [
                    "🆕 NEWLY ADDED - Modern university (1990)",
                    "Data Science specialty focus",
                    "Barcelona 22@ Innovation District",
                    "Smaller than UB - personalized",
                    "Strong international orientation",
                    "Bilingual Spanish/English",
                    "Competitive Barcelona tuition",
                    "Excellent modern alternative to UB"
                ],
                url: "https://www.upf.edu/web/graus/grau-en-ciencia-de-dades"
            },

            // FRANCE (3 universities)
            {
                id: 28,
                name: "PSL Paris",
                country: "France",
                program: "International BSc AI",
                language: "English",
                lat: 48.8434,
                lng: 2.3380,
                tuitionPerYear: "€13,000",
                livingPerYear: "€14,400-18,000",
                duration: 3,
                cost: "€82-93k total",
                costMin: 82000,
                costMax: 93000,
                erasmusPlus: true,
                erasmusPartners: "Elite network",
                classification: "Elite Reach",
                fitScore: 5,
                citySize: "Large city",
                admissionsEmail: "admissions@psl.eu",
                openHouseDates: "Check website",
                visitInfo: "Campus tours by appointment",
                visitUrl: "https://www.psl.eu/en/education/bachelors-degree/psl-international-bachelors-degree-sciences",
                highlights: [
                    "ELITE program (highly selective)",
                    "English-taught international track",
                    "PSL network (ENS, École Polytechnique)",
                    "EXPENSIVE for France (€82-93k)"
                ],
                url: "https://www.psl.eu/en/education/bachelors-degree/psl-international-bachelors-degree-sciences"
            },
            {
                id: 29,
                name: "Paris-Saclay",
                country: "France",
                program: "BSc CS + AI track",
                language: "French/English",
                lat: 48.7128,
                lng: 2.2059,
                tuitionPerYear: "€170",
                livingPerYear: "€14,400-16,800",
                duration: 3,
                cost: "€44-51k total",
                costMin: 44000,
                costMax: 51000,
                erasmusPlus: true,
                erasmusPartners: "200+",
                classification: "Match",
                fitScore: 4,
                citySize: "Paris suburbs",
                admissionsEmail: "contact@universite-paris-saclay.fr",
                openHouseDates: "Spring 2026",
                visitInfo: "Campus tours available",
                visitUrl: "https://www.universite-paris-saclay.fr/en",
                highlights: [
                    "STATUTORY French tuition (€170/year!)",
                    "Mostly French-taught",
                    "Alliance 4EU+ network",
                    "Paris area location"
                ],
                url: "https://www.universite-paris-saclay.fr/en"
            },
            {
                id: 30,
                name: "DSTI Paris",
                country: "France",
                program: "BSc Data Science & AI (PRIVATE)",
                language: "English",
                lat: 48.8566,
                lng: 2.3522,
                tuitionPerYear: "€9,000-10,000",
                livingPerYear: "€14,400-18,000",
                duration: 3,
                cost: "€70-84k total",
                costMin: 70000,
                costMax: 84000,
                erasmusPlus: false,
                erasmusPartners: "None",
                classification: "Expensive",
                fitScore: 3,
                citySize: "Large city",
                admissionsEmail: "info@dsti.education",
                openHouseDates: "Check website",
                visitInfo: "Campus tours by appointment",
                visitUrl: "https://www.datasciencetech.institute/",
                highlights: [
                    "English-taught private school",
                    "EXPENSIVE (€70-84k)",
                    "No Erasmus+ (private institution)",
                    "NOT recommended - poor value"
                ],
                url: "https://www.datasciencetech.institute/"
            },

            // AUSTRIA (2 universities)
            {
                id: 31,
                name: "JKU Linz",
                country: "Austria",
                program: "BSc Artificial Intelligence",
                language: "English",
                lat: 48.3369,
                lng: 14.3193,
                tuitionPerYear: "€151",
                livingPerYear: "€9,600-14,400",
                duration: 3,
                cost: "€29-43k total",
                costMin: 29000,
                costMax: 43000,
                erasmusPlus: true,
                erasmusPartners: "200+",
                classification: "Match",
                fitScore: 5,
                citySize: "Mid-size city",
                admissionsEmail: "study@jku.at",
                openHouseDates: "Spring 2026",
                visitInfo: "Campus tours available",
                visitUrl: "https://www.jku.at/en/degree-programs/bachelors-programmes/ba-artificial-intelligence/",
                highlights: [
                    "One of Europe's first AI programs",
                    "Near-free tuition (€25.20/semester)",
                    "Affordable Austrian city",
                    "Strong tech industry presence"
                ],
                url: "https://www.jku.at/en/degree-programs/bachelors-programmes/ba-artificial-intelligence/"
            },
            {
                id: 38,
                name: "FH St. Pölten",
                country: "Austria",
                program: "BSc Data Science & AI",
                language: "English",
                lat: 48.2039,
                lng: 15.6266,
                tuitionPerYear: "€726",
                livingPerYear: "€9,600-14,400",
                duration: 3,
                cost: "€29-41k total",
                costMin: 29000,
                costMax: 41000,
                erasmusPlus: true,
                erasmusPartners: "150+",
                classification: "Match",
                fitScore: 5,
                citySize: "Mid-size city",
                admissionsEmail: "csc@fhstp.ac.at",
                openHouseDates: "Fall 2025",
                visitInfo: "Campus tours and info sessions",
                visitUrl: "https://www.ustp.at/en/study-programmes/computer-science-security/data-science-and-artificial-intelligence",
                highlights: [
                    "Data Science focus (perfect for Sophia!)",
                    "25 min from Vienna by train",
                    "Applied sciences - industry-ready",
                    "Modern curriculum combining AI & analytics"
                ],
                url: "https://www.ustp.at/en/study-programmes/computer-science-security/data-science-and-artificial-intelligence"
            },

            // ITALY (3 universities)
            {
                id: 32,
                name: "University of Milan",
                country: "Italy",
                program: "BSc Artificial Intelligence",
                language: "English",
                lat: 45.4642,
                lng: 9.1900,
                tuitionPerYear: "€2,000-3,000",
                livingPerYear: "€12,000-14,400",
                duration: 3,
                cost: "€42-52k total",
                costMin: 42000,
                costMax: 52000,
                erasmusPlus: true,
                erasmusPartners: "400+",
                classification: "Match",
                fitScore: 4,
                citySize: "Large city",
                admissionsEmail: "info@unimi.it",
                openHouseDates: "Spring 2026",
                visitInfo: "Campus tours available",
                visitUrl: "https://www.unimi.it/en",
                highlights: [
                    "English-taught program",
                    "Fashion capital location",
                    "Erasmus+ with 400+ partners (very extensive)",
                    "Milan living costs HIGH"
                ],
                url: "https://www.unimi.it/en/education/bachelor-programme/artificial-intelligence"
            },
            {
                id: 33,
                name: "University of Pavia",
                country: "Italy",
                program: "BSc Artificial Intelligence",
                language: "English",
                lat: 45.1847,
                lng: 9.1582,
                tuitionPerYear: "€1,500-2,500",
                livingPerYear: "€9,600-10,800",
                duration: 3,
                cost: "€33-40k total",
                costMin: 33000,
                costMax: 40000,
                erasmusPlus: true,
                erasmusPartners: "300+",
                classification: "Match",
                fitScore: 4,
                citySize: "Mid-size city",
                admissionsEmail: "internationaladmissions@unipv.it",
                openHouseDates: "Multiple dates",
                visitInfo: "Campus tours available",
                visitUrl: "https://web.unipv.it/artificial-intelligence/",
                highlights: [
                    "English-taught AI program",
                    "VERY AFFORDABLE (€33-40k)",
                    "Historic Italian city",
                    "Coimbra Group member"
                ],
                url: "https://web.unipv.it/artificial-intelligence/"
            },
            {
                id: 34,
                name: "H-FARM College",
                country: "Italy",
                program: "BSc AI & Data Science (PRIVATE)",
                language: "English",
                lat: 45.6495,
                lng: 12.2422,
                tuitionPerYear: "€12,000-14,000",
                livingPerYear: "€12,000-13,200",
                duration: 3,
                cost: "€72-82k total",
                costMin: 72000,
                costMax: 82000,
                erasmusPlus: false,
                erasmusPartners: "None",
                classification: "Expensive",
                fitScore: 3,
                citySize: "Venice area",
                admissionsEmail: "admissions@h-farm.com",
                openHouseDates: "Check website",
                visitInfo: "Campus tours by appointment",
                visitUrl: "https://www.h-farmcollege.com/",
                highlights: [
                    "English-taught private school",
                    "Startup/entrepreneurship focus",
                    "EXPENSIVE (€72-82k)",
                    "No Erasmus+ (private)"
                ],
                url: "https://www.h-farmcollege.com/undergraduate/artificial-intelligence-and-data-science"
            },

            // SWEDEN (1 university)
            {
                id: 35,
                name: "Karlstad University",
                country: "Sweden",
                program: "BSc CS (AI & ML track)",
                language: "English",
                lat: 59.3793,
                lng: 13.5036,
                tuitionPerYear: "€0",
                livingPerYear: "€12,000-13,200",
                duration: 3,
                cost: "€36-40k total",
                costMin: 36000,
                costMax: 40000,
                erasmusPlus: true,
                erasmusPartners: "300+",
                classification: "Safety",
                fitScore: 4,
                citySize: "Mid-size city",
                admissionsEmail: "admissions@kau.se",
                openHouseDates: "Spring 2026",
                visitInfo: "Campus tours available",
                visitUrl: "https://www.kau.se/en/education/programmes-and-courses/programmes/SGDSC",
                highlights: [
                    "FREE tuition for EU students",
                    "English-taught program",
                    "Swedish quality of life",
                    "Nordplus network participant"
                ],
                url: "https://www.kau.se/en/education/programmes-and-courses/programmes/SGDSC"
            },

            // PORTUGAL (1 university)
            {
                id: 36,
                name: "NOVA IMS Lisbon",
                country: "Portugal",
                program: "BSc Data Science",
                language: "English",
                lat: 38.7223,
                lng: -9.1393,
                tuitionPerYear: "€697",
                livingPerYear: "€7,200-9,600",
                duration: 3,
                cost: "€24-31k total",
                costMin: 24000,
                costMax: 31000,
                erasmusPlus: true,
                erasmusPartners: "100+",
                classification: "Match",
                fitScore: 5,
                citySize: "Large city",
                admissionsEmail: "admissions@novaims.unl.pt",
                openHouseDates: "Spring 2026",
                visitInfo: "Campus tours available",
                visitUrl: "https://www.novaims.unl.pt/education/bachelors/data-science",
                highlights: [
                    "100% ENGLISH-taught",
                    "MOST AFFORDABLE (€24-31k total!)",
                    "Dedicated Data Science school",
                    "Excellent value proposition"
                ],
                url: "https://www.novaims.unl.pt/education/bachelors/data-science",
                new: true
            }
        ];